spring.application.name=gymbackend
spring.datasource.url=jdbc:postgresql://localhost:5432/gymsystem
spring.datasource.username=postgres
spring.datasource.password=Caczmareki@147

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true